### ISSUE TITLE
Error sending a picture bigger than 10Mb

### ISSUE THREAD

**Issue by andrw00** [zhukov/webogram#1011]
This error appears when trying to send a picture (not a file) that is > 10Mb

Method: messages.sendMedia
Result: {"_":"rpc_error","error_code":400,"error_message":"PHOTO_SAVE_FILE_INVALID"}
Stack: Error
    at u (https://web.telegram.org/js/app.js:18:3697)
    at https://web.telegram.org/js/app.js:18:4996
    at l (https://web.telegram.org/js/app.js:8:11738)
    at https://web.telegram.org/js/app.js:8:11910
    at m.$eval (https://web.telegram.org/js/app.js:8:19316)
    at m.$digest (https://web.telegram.org/js/app.js:8:17747)
    at https://web.telegram.org/js/app.js:8:19403
    at a (https://web.telegram.org/js/app.js:7:2845)
    at https://web.telegram.org/js/app.js:7:4299
    at n (https://web.telegram.org/js/app.js:2:17073)

**Comment by zhukov** [comment]
Telegram currently doesn't support sending photos larger than 5MB.
