### ISSUE TITLE
Network error while sign in to telegram web

### ISSUE THREAD

**Issue by biswatmanayak** [zhukov/webogram#1075]
> Method: auth.sendCode
Url: https://venus.web.telegram.org/apiw1
Result: {"data":null,"status":-1,"config":{"method":"POST","transformRequest":null,"transformResponse":[null],"responseType":"arraybuffer","url":"https://venus.web.telegram.org/apiw1","data":{"0":0,"1":0,"2":214248604,"3":1456754077,"4":20,"5":1615239032,"6":-630033320,"7":1283856274,"8":1197968614,"9":-33336297},"headers":{}},"statusText":""}
Stack: Error
    at rejectPromise (http://localhost:8000/app/js/lib/mtproto_wrapper.js:136:95)
    at processQueue (http://localhost:8000/app/vendor/angular/angular.js:14745:28)
    at http://localhost:8000/app/vendor/angular/angular.js:14761:27
    at Scope.$eval (http://localhost:8000/app/vendor/angular/angular.js:15989:28)
    at Scope.$digest (http://localhost:8000/app/vendor/angular/angular.js:15800:31)
    at Scope.$apply (http://localhost:8000/app/vendor/angular/angular.js:16097:24)
    at done (http://localhost:8000/app/vendor/angular/angular.js:10546:47)
    at completeRequest (http://localhost:8000/app/vendor/angular/angular.js:10744:7)
    at XMLHttpRequest.requestError (http://localhost:8000/app/vendor/angular/angular.js:10695:9)

**Comment by biswatmanayak** [comment]
seems there was a network issue from my side 
I just changed ip and worked 
closing the issue
