### ISSUE TITLE
install on mac is shows Error: Cannot find module 'once'

### ISSUE THREAD

**Issue by lilien1010** [zhukov/webogram#1110]
when I run  `gulp watch` ,It show              
module.js:338
    throw err;
          ^
Error: Cannot find module 'once'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/admin/Documents/webogram/node_modules/gulp/node_modules/orchestrator/node_modules/end-of-stream/index.js:1:74)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
➜  webogram git:(master)

**Comment by zhukov** [comment]
did you run ```sh
$ sudo npm install -g gulp
npm install```?

**Comment by Pastuhanov** [comment]
я не могу понять как это работает


2016-06-06 20:58 GMT+03:00 Igor Zhukov <notifications@github.com>:
