### ISSUE TITLE
Reply with empty field

### ISSUE THREAD

**Issue by ggfaggot** [zhukov/webogram#1125]
If u make reply in current chat u cannot post it without a comment and if u insert some spaces it falls 
with:
```
Method: messages.sendMessage
Url: N/A
Result: {"_":"rpc_error","error_code":400,"error_message":"MESSAGE_EMPTY"}
Stack: Error
    at Object.g [as invokeApi] (https://web.telegram.org/js/app.js:31:11150)
    at Z.i.send (https://web.telegram.org/js/app.js:39:17159)
    at n (https://web.telegram.org/js/app.js:3:17055)
```

**Comment by kiddick** [comment]
+1
