### ISSUE TITLE
Getting error messages.getBotCallbackAnswer MESSAGE_ID_INVALID in bot inline buttons after editMessageReplyMarkup

### ISSUE THREAD

**Issue by ihoru** [zhukov/webogram#1133]
Steps:
1. Open dialog with a bot.
2. A bot sends message with inline button (with callback_data).
3. Tap the button
4. A bot gets an update (CallbackQuery) and sends request editMessageReplyMarkup with empty reply_markup to the message from 2 step
5. After some waiting (20+ seconds) error window appears with such trace:
```
Method: messages.getBotCallbackAnswer
Url: N/A
Result: {"_":"rpc_error","error_code":400,"error_message":"MESSAGE_ID_INVALID"}
Stack: Error
    at Object.g [as invokeApi] (https://web.telegram.org/js/app.js:31:11150)
    at Object.C [as callbackButtonClick] (https://web.telegram.org/js/app.js:32:24562)
    at https://web.telegram.org/js/app.js:52:11119
    at m.$emit (https://web.telegram.org/js/app.js:16:4877)
    at m.e.buttonClick (https://web.telegram.org/js/app.js:52:14421)
    at https://web.telegram.org/js/app.js:17:26445
    at https://web.telegram.org/js/app.js:22:1736
    at m.$eval (https://web.telegram.org/js/app.js:16:3938)
    at m.$apply (https://web.telegram.org/js/app.js:16:4168)
    at HTMLButtonElement.<anonymous> (https://web.telegram.org/js/app.js:22:1718)
```

BTW, the button disappears.

**Comment by ihoru** [comment]
Duplicate of: https://github.com/zhukov/webogram/issues/1129
