### ISSUE TITLE
Unable to create a group

### ISSUE THREAD

**Issue by jurgob** [zhukov/webogram#1137]
When I try to create a group, I have the following error:

```bash
Method: messages.createChat
Url: N/A
Result: {"_":"rpc_error","error_code":403,"error_message":"USER_RESTRICTED"}
Stack: Error
    at Object.g [as invokeApi] (https://web.telegram.org/js/app.js:31:11150)
    at m.e.createGroup (https://web.telegram.org/js/app.js:38:22906)
    at https://web.telegram.org/js/app.js:17:26445
    at https://web.telegram.org/js/app.js:22:1736
    at m.$eval (https://web.telegram.org/js/app.js:16:3938)
    at m.$apply (https://web.telegram.org/js/app.js:16:4168)
    at HTMLButtonElement.<anonymous> (https://web.telegram.org/js/app.js:22:1718)
    at HTMLButtonElement.ie.event.dispatch (https://web.telegram.org/js/app.js:5:2788)
    at HTMLButtonElement.f.handle (https://web.telegram.org/js/app.js:4:31558)
```

I've tryied also on the 2 desktop apps for mac and from the android app, but I'm not able to create groups.
I'm posting it here cuz I don't have any idea about how to notify this to the api creators :P

**Comment by zhukov** [comment]
Please contact Telegram support: https://telegram.org/faq#telegram-support

**Comment by mshkrebtan** [comment]
I get the same error. And Telegram support is not responding...
