### ISSUE TITLE
error message when you insert space

### ISSUE THREAD

**Issue by franklinbr** [zhukov/webogram#1138]
Show a modal with erros, see down:

Method: messages.sendMessage
Url: N/A
Result: {"_":"rpc_error","error_code":400,"error_message":"MESSAGE_EMPTY"}
Stack: Error
    at Object.g [as invokeApi] (https://web.telegram.org/js/app.js:31:11150)
    at Z.i.send (https://web.telegram.org/js/app.js:39:17159)
    at n (https://web.telegram.org/js/app.js:3:17055)

**Comment by zhukov** [comment]
Duplicate #1125
