### ISSUE TITLE
gulp publish gives throw er; // Unhandled stream error in pipe.

### ISSUE THREAD

**Issue by ecast040** [zhukov/webogram#1193]
The full error was this, it should work out of the box but for some reason it gives this error after using the command gulp publish

Error: write after end
    at writeAfterEnd (D:\webogram-master\webogram-master\node_modules\gulp-minify-css\node_modules\through2\node_modules\readable-stream\lib_stream_writable.js:144:12)
    at DestroyableTransform.Writable.write (D:\webogram-master\webogram-master\node_modules\gulp-minify-css\node_modules\through2\node_modules\readable-stream\lib_stream_writable.js:192:5)
    at Stream.ondata (stream.js:31:26)
    at emitOne (events.js:77:13)
    at Stream.emit (events.js:169:7)
    at Stream.endStream (D:\webogram-master\webogram-master\node_modules\gulp-usemin\node_modules\gulp-concat\index.js:90:10)
    at _end (D:\webogram-master\webogram-master\node_modules\gulp-usemin\node_modules\gulp-concat\node_modules\through\index.js:65:9)
    at Stream.stream.end (D:\webogram-master\webogram-master\node_modules\gulp-usemin\node_modules\gulp-concat\node_modules\through\index.js:74:5)
    at Transform.onend (D:\webogram-master\webogram-master\node_modules\gulp-usemin\node_modules\through2\node_modules\readable-stream\lib_stream_readable.js:523:10)
    at Transform.g (events.js:260:16)

**Comment by zhukov** [comment]
I think we've fixed this in #956
Please try to reinstall all npm packages, update sources etc.
