### ISSUE TITLE
Can't sign up (rpc_error, MEMBER_NO_LOCATION)

### ISSUE THREAD

**Issue by kalemas** [zhukov/webogram#1204]
I haven't done anything special. Entered phone number (+79057698868), entered received verification code, entered user name, pressed Next. But got following:

`
Method: auth.signUp
Url: N/A
Result: {"_":"rpc_error","error_code":500,"error_message":"MEMBER_NO_LOCATION"}
Stack: Error
    at Object.h [as invokeApi] (https://web.telegram.org/js/app.js:23:25735)
    at g.e.logIn (https://web.telegram.org/js/app.js:26:8027)
    at https://web.telegram.org/js/app.js:15:7420
    at t (https://web.telegram.org/js/app.js:13:2586)
    at a (https://web.telegram.org/js/app.js:15:17764)
    at g.$eval (https://web.telegram.org/js/app.js:13:12666)
    at g.$apply (https://web.telegram.org/js/app.js:13:12899)
    at HTMLAnchorElement.<anonymous> (https://web.telegram.org/js/app.js:15:17816)
    at HTMLAnchorElement.dispatch (https://web.telegram.org/js/app.js:4:2788)
    at HTMLAnchorElement.f.handle (https://web.telegram.org/js/app.js:3:31557)
`

**Comment by zhukov** [comment]
This is a server-side issue. Please report it to Telegram Support.
