### ISSUE TITLE
Problem when join group

### ISSUE THREAD

**Issue by diffanet** [zhukov/webogram#1252]
When i join group, suddenly it comes. Why?

![image](https://cloud.githubusercontent.com/assets/14326798/19688856/8c09c838-9af5-11e6-9bb1-df00685555a4.png)

Method: contacts.resolveUsername
Url: N/A
Result: {"_":"rpc_error","error_code":420,"error_message":"FLOOD_WAIT_47435"}
Stack: Error
    at Object.h [as invokeApi](https://web.telegram.org/js/app.js:23:25735)
    at Object.d [as resolveUsername](https://web.telegram.org/js/app.js:24:15239)
    at g (https://web.telegram.org/js/app.js:25:28235)
    at m (https://web.telegram.org/js/app.js:25:28121)
    at Object.f [as start](https://web.telegram.org/js/app.js:25:31073)
    at new <anonymous> (https://web.telegram.org/js/app.js:26:13653)
    at Object.r [as instantiate](https://web.telegram.org/js/app.js:11:21370)
    at https://web.telegram.org/js/app.js:12:15279
    at Object.link (https://web.telegram.org/js/app.js:16:12334)
    at https://web.telegram.org/js/app.js:11:6148

**Comment by diffanet** [comment]
someone help me :(

**Comment by stek29** [comment]
Just wait

**Comment by diffanet** [comment]
solved, thanks :)

**Comment by Ryuno-Ki** [comment]
@diffanet Please close the issue then.
