### ISSUE TITLE
SMS code cannot be generated

### ISSUE THREAD

**Issue by webschik** [zhukov/webogram#1540]
Hi,

I cannot get the code via SMS (country code +31):

<img width="977" alt="telegram_console" src="https://user-images.githubusercontent.com/1665314/32291190-a7164482-bf3c-11e7-81ea-a83fc39a68f1.png">
  

The 406th error:

```js
{
  "code": 406,
  "type": "NETWORK_BAD_RESPONSE",
  "url": "https://vesta.web.telegram.org/apiw1",
  "originalError": {
    "data": null,
    "status": -1,
    "config": {
      "method": "POST",
      "transformRequest": null,
      "transformResponse": [
        null
      ],
      "responseType": "arraybuffer",
      "url": "https://vesta.web.telegram.org/apiw1",
      "data": {
        "0": 0,
        "1": 0,
        "2": 1816188852,
        "3": 1509561486,
        "4": 20,
        "5": 1615239032,
        "6": -412584228,
        "7": -1262741654,
        "8": 986316058,
        "9": 389744170
      },
      "headers": {}
    },
    "statusText": ""
  },
  "handled": true,
  "input": "auth.sendCode",
  "stack": "Error\n    at Object.g [as invokeApi] (https://web.telegram.org/js/app.js:59:16264)\n    at https://web.telegram.org/js/app.js:62:2249\n    at o (https://web.telegram.org/js/app.js:14:4253)\n    at https://web.telegram.org/js/app.js:14:4425\n    at m.$eval (https://web.telegram.org/js/app.js:14:11972)\n    at m.$digest (https://web.telegram.org/js/app.js:14:10458)\n    at m.$apply (https://web.telegram.org/js/app.js:14:12255)\n    at HTMLButtonElement.<anonymous> (https://web.telegram.org/js/app.js:16:17126)\n    at HTMLButtonElement.dispatch (https://web.telegram.org/js/app.js:4:3231)\n    at HTMLButtonElement.g.handle (https://web.telegram.org/js/app.js:3:31927)"
}
```

**Comment by stek29** [comment]
Is this still relevant?

**Comment by webschik** [comment]
Probably we can close this issue. I found that it happens only with the active Parental control mode on macOS Sierra. The interesting thing there that I don't have any active restrictions for web pages, etc.
