### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by l0k9j8** [zhukov/webogram#1863]
npm run build output:
```
> gulp publish

[11:38:47] Using gulpfile ~/Work/webogram/gulpfile.js
[11:38:47] Starting 'publish'...
[11:38:47] Starting 'add-appcache-manifest'...
[11:38:47] Starting 'build'...
[11:38:47] Starting 'clean'...
[11:38:48] Finished 'clean' after 18 ms
[11:38:48] Starting 'less'...
[11:38:48] Starting 'templates'...
[11:38:48] Finished 'less' after 381 ms
[11:38:48] Finished 'templates' after 489 ms
[11:38:48] Starting 'enable-production'...
[11:38:48] Starting '<anonymous>'...
[11:38:48] Starting '<anonymous>'...
[11:38:48] Finished '<anonymous>' after 298 ms
[11:38:49] Finished '<anonymous>' after 1.41 s
[11:38:49] Finished 'enable-production' after 1.41 s
[11:38:49] Starting 'usemin-index'...
[11:39:05] Finished 'usemin-index' after 15 s
[11:39:05] Starting 'usemin-badbrowser'...
[11:39:05] Finished 'usemin-badbrowser' after 200 ms
[11:39:05] Starting 'copy'...
[11:39:05] Starting 'copy-locales'...
[11:39:05] Starting 'copy-images'...
[11:39:05] Starting 'disable-production'...
[11:39:05] Starting '<anonymous>'...
[11:39:05] Starting '<anonymous>'...
[11:39:05] Starting '<anonymous>'...
[11:39:05] Starting '<anonymous>'...
[11:39:05] Starting '<anonymous>'...
[11:39:05] Starting '<anonymous>'...
[11:39:05] Starting '<anonymous>'...
[11:39:05] Starting '<anonymous>'...
[11:39:05] Starting '<anonymous>'...
[11:39:05] Starting '<anonymous>'...
[11:39:05] Starting '<anonymous>'...
[11:39:05] Starting '<anonymous>'...
[11:39:05] Starting '<anonymous>'...
[11:39:05] Starting '<anonymous>'...
[11:39:05] Starting '<anonymous>'...
[11:39:05] Finished '<anonymous>' after 57 ms
[11:39:05] Finished '<anonymous>' after 158 ms
[11:39:05] Finished '<anonymous>' after 155 ms
[11:39:05] Finished '<anonymous>' after 163 ms
[11:39:05] Finished '<anonymous>' after 163 ms
[11:39:05] Finished '<anonymous>' after 163 ms
[11:39:05] Finished '<anonymous>' after 163 ms
[11:39:05] Finished '<anonymous>' after 164 ms
[11:39:05] Finished '<anonymous>' after 171 ms
[11:39:05] Finished '<anonymous>' after 171 ms
[11:39:05] Finished '<anonymous>' after 170 ms
[11:39:05] Finished '<anonymous>' after 187 ms
[11:39:05] Finished '<anonymous>' after 206 ms
[11:39:05] Finished 'copy' after 207 ms
[11:39:05] Finished '<anonymous>' after 227 ms
[11:39:05] Finished 'copy-locales' after 231 ms
[11:39:05] Finished 'copy-images' after 423 ms
[11:39:06] Finished '<anonymous>' after 1.21 s
[11:39:06] Finished 'disable-production' after 1.22 s
[11:39:06] Starting 'clean-templates'...
[11:39:06] Finished 'clean-templates' after 4.81 ms
[11:39:06] Finished 'build' after 19 s
[11:39:06] Starting '<anonymous>'...
[11:39:06] '<anonymous>' errored after 78 ms
[11:39:06] Error: Received a non-Vinyl object in `dest()`
    at DestroyableTransform.normalize [as _transform] (/Users/user/Work/webogram/node_modules/vinyl-fs/lib/dest/prepare.js:16:17)
    at DestroyableTransform.Transform._read (/Users/user/Work/webogram/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/Users/user/Work/webogram/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:83)
    at doWrite (/Users/user/Work/webogram/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:428:64)
    at writeOrBuffer (/Users/user/Work/webogram/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:417:5)
    at DestroyableTransform.Writable.write (/Users/user/Work/webogram/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:334:11)
    at Pumpify.Duplexify._write (/Users/user/Work/webogram/node_modules/duplexify/index.js:208:22)
    at doWrite (/Users/user/Work/webogram/node_modules/duplexify/node_modules/readable-stream/lib/_stream_writable.js:428:64)
    at writeOrBuffer (/Users/user/Work/webogram/node_modules/duplexify/node_modules/readable-stream/lib/_stream_writable.js:417:5)
    at Pumpify.Writable.write (/Users/user/Work/webogram/node_modules/duplexify/node_modules/readable-stream/lib/_stream_writable.js:334:11)
    at Stream.ondata (internal/streams/legacy.js:17:31)
    at Stream.emit (events.js:200:13)
    at Stream.EventEmitter.emit (domain.js:494:23)
    at Stream.endStream (/Users/user/Work/webogram/node_modules/gulp-manifest/index.js:130:10)
    at _end (/Users/user/Work/webogram/node_modules/through/index.js:65:9)
    at Stream.stream.end (/Users/user/Work/webogram/node_modules/through/index.js:74:5)
[11:39:06] 'add-appcache-manifest' errored after 19 s
[11:39:06] 'publish' errored after 19 s
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! Telegram@0.7.0 build: `gulp publish`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the Telegram@0.7.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/user/.npm/_logs/2019-06-14T08_39_06_812Z-debug.log
```
2019-06-14T08_39_06_812Z-debug.log content:
```
cat /Users/user/.npm/_logs/2019-06-14T08_39_06_812Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/local/Cellar/node/12.4.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build'
1 verbose cli ]
2 info using npm@6.9.0
3 info using node@v12.4.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle Telegram@0.7.0~prebuild: Telegram@0.7.0
6 info lifecycle Telegram@0.7.0~build: Telegram@0.7.0
7 verbose lifecycle Telegram@0.7.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle Telegram@0.7.0~build: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/user/Work/webogram/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/user/Work/GoDev/bin
9 verbose lifecycle Telegram@0.7.0~build: CWD: /Users/user/Work/webogram
10 silly lifecycle Telegram@0.7.0~build: Args: [ '-c', 'gulp publish' ]
11 silly lifecycle Telegram@0.7.0~build: Returned: code: 1  signal: null
12 info lifecycle Telegram@0.7.0~build: Failed to exec build script
13 verbose stack Error: Telegram@0.7.0 build: `gulp publish`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:200:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:200:13)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
14 verbose pkgid Telegram@0.7.0
15 verbose cwd /Users/user/Work/webogram
16 verbose Darwin 18.6.0
17 verbose argv "/usr/local/Cellar/node/12.4.0/bin/node" "/usr/local/bin/npm" "run" "build"
18 verbose node v12.4.0
19 verbose npm  v6.9.0
20 error code ELIFECYCLE
21 error errno 1
22 error Telegram@0.7.0 build: `gulp publish`
22 error Exit status 1
23 error Failed at the Telegram@0.7.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by Nill-R** [comment]
And me to have same problem

`npm run build`

`> Telegram@0.7.0 build /root/webogram`
`> gulp publish`

```
[03:16:49] Using gulpfile ~/webogram/gulpfile.js
[03:16:49] Starting 'publish'...
[03:16:49] Starting 'add-appcache-manifest'...
[03:16:49] Starting 'build'...
[03:16:49] Starting 'clean'...
[03:16:49] Finished 'clean' after 63 ms
[03:16:49] Starting 'less'...
[03:16:49] Starting 'templates'...
[03:16:50] Finished 'less' after 992 ms
[03:16:50] Finished 'templates' after 1.12 s
[03:16:50] Starting 'enable-production'...
[03:16:50] Starting '<anonymous>'...
[03:16:50] Starting '<anonymous>'...
[03:16:51] Finished '<anonymous>' after 841 ms
[03:16:52] Finished '<anonymous>' after 1.67 s
[03:16:52] Finished 'enable-production' after 1.67 s
[03:16:52] Starting 'usemin-index'...
[03:17:30] Finished 'usemin-index' after 38 s
[03:17:30] Starting 'usemin-badbrowser'...
[03:17:30] Finished 'usemin-badbrowser' after 415 ms
[03:17:30] Starting 'copy'...
[03:17:30] Starting 'copy-locales'...
[03:17:30] Starting 'copy-images'...
[03:17:30] Starting 'disable-production'...
[03:17:30] Starting '<anonymous>'...
[03:17:30] Starting '<anonymous>'...
[03:17:30] Starting '<anonymous>'...
[03:17:30] Starting '<anonymous>'...
[03:17:30] Starting '<anonymous>'...
[03:17:30] Starting '<anonymous>'...
[03:17:30] Starting '<anonymous>'...
[03:17:30] Starting '<anonymous>'...
[03:17:30] Starting '<anonymous>'...
[03:17:30] Starting '<anonymous>'...
[03:17:30] Starting '<anonymous>'...
[03:17:30] Starting '<anonymous>'...
[03:17:30] Starting '<anonymous>'...
[03:17:30] Starting '<anonymous>'...
[03:17:30] Starting '<anonymous>'...
[03:17:30] Finished '<anonymous>' after 92 ms
[03:17:31] Finished '<anonymous>' after 325 ms
[03:17:31] Finished '<anonymous>' after 329 ms
[03:17:31] Finished '<anonymous>' after 329 ms
[03:17:31] Finished '<anonymous>' after 329 ms
[03:17:31] Finished '<anonymous>' after 330 ms
[03:17:31] Finished '<anonymous>' after 330 ms
[03:17:31] Finished '<anonymous>' after 336 ms
[03:17:31] Finished '<anonymous>' after 337 ms
[03:17:31] Finished '<anonymous>' after 337 ms
[03:17:31] Finished '<anonymous>' after 368 ms
[03:17:31] Finished '<anonymous>' after 369 ms
[03:17:31] Finished 'copy-locales' after 371 ms
[03:17:31] Finished '<anonymous>' after 382 ms
[03:17:31] Finished 'copy' after 383 ms
[03:17:31] Finished '<anonymous>' after 388 ms
[03:17:31] Finished 'copy-images' after 655 ms
[03:17:32] Finished '<anonymous>' after 1.45 s
[03:17:32] Finished 'disable-production' after 1.46 s
[03:17:32] Starting 'clean-templates'...
[03:17:32] Finished 'clean-templates' after 3.8 ms
[03:17:32] Finished 'build' after 43 s
[03:17:32] Starting '<anonymous>'...
[03:17:32] '<anonymous>' errored after 127 ms
[03:17:32] Error: Received a non-Vinyl object in `dest()`
    at DestroyableTransform.normalize [as _transform] (/root/webogram/node_modules/vinyl-fs/lib/dest/prepare.js:16:17)
    at DestroyableTransform.Transform._read (/root/webogram/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/root/webogram/node_modules/readable-stream/lib/_stream_transform.js:172:83)
    at doWrite (/root/webogram/node_modules/readable-stream/lib/_stream_writable.js:428:64)
    at writeOrBuffer (/root/webogram/node_modules/readable-stream/lib/_stream_writable.js:417:5)
    at DestroyableTransform.Writable.write (/root/webogram/node_modules/readable-stream/lib/_stream_writable.js:334:11)
    at Pumpify.Duplexify._write (/root/webogram/node_modules/duplexify/index.js:208:22)
    at doWrite (/root/webogram/node_modules/readable-stream/lib/_stream_writable.js:428:64)
    at writeOrBuffer (/root/webogram/node_modules/readable-stream/lib/_stream_writable.js:417:5)
    at Pumpify.Writable.write (/root/webogram/node_modules/readable-stream/lib/_stream_writable.js:334:11)
    at Stream.ondata (internal/streams/legacy.js:16:26)
    at emitOne (events.js:116:13)
    at Stream.emit (events.js:211:7)
    at Stream.endStream (/root/webogram/node_modules/gulp-manifest/index.js:130:10)
    at _end (/root/webogram/node_modules/through/index.js:65:9)
    at Stream.stream.end (/root/webogram/node_modules/through/index.js:74:5)
[03:17:32] 'add-appcache-manifest' errored after 43 s
[03:17:32] 'publish' errored after 43 s

npm ERR! Linux 4.15.0-48-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! Telegram@0.7.0 build: `gulp publish`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the Telegram@0.7.0 build script 'gulp publish'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the Telegram package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp publish
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs Telegram
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls Telegram
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/webogram/npm-debug.log`
```

And npm-debug.log

```
2 info using npm@3.5.2
3 info using node@v8.10.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle Telegram@0.7.0~prebuild: Telegram@0.7.0
6 silly lifecycle Telegram@0.7.0~prebuild: no script for prebuild, continuing
7 info lifecycle Telegram@0.7.0~build: Telegram@0.7.0
8 verbose lifecycle Telegram@0.7.0~build: unsafe-perm in lifecycle true
9 verbose lifecycle Telegram@0.7.0~build: PATH: /usr/share/npm/bin/node-gyp-bin:/root/webogram/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
10 verbose lifecycle Telegram@0.7.0~build: CWD: /root/webogram
11 silly lifecycle Telegram@0.7.0~build: Args: [ '-c', 'gulp publish' ]
12 silly lifecycle Telegram@0.7.0~build: Returned: code: 1  signal: null
13 info lifecycle Telegram@0.7.0~build: Failed to exec build script
14 verbose stack Error: Telegram@0.7.0 build: `gulp publish`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/lib/utils/lifecycle.js:232:16)
14 verbose stack     at emitTwo (events.js:126:13)
14 verbose stack     at EventEmitter.emit (events.js:214:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:126:13)
14 verbose stack     at ChildProcess.emit (events.js:214:7)
14 verbose stack     at maybeClose (internal/child_process.js:925:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
15 verbose pkgid Telegram@0.7.0
16 verbose cwd /root/webogram
17 error Linux 4.15.0-48-generic
18 error argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
19 error node v8.10.0
20 error npm  v3.5.2
21 error code ELIFECYCLE
22 error Telegram@0.7.0 build: `gulp publish`
22 error Exit status 1
23 error Failed at the Telegram@0.7.0 build script 'gulp publish'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the Telegram package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     gulp publish
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs Telegram
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls Telegram
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by renhaoweixiao** [comment]
yeah, same problem

**Comment by MatamVamshiKrishna** [comment]
[gulpfile.js.zip](https://github.com/zhukov/webogram/files/3344451/gulpfile.js.zip)

I made a few changes to gulpfile.js. This could successfully build my project. Use any file diff checker to see the changes. Also, the build was running twice, I made it run only once.

**Comment by MatamVamshiKrishna** [comment]
[gulpfile.js.zip](https://github.com/zhukov/webogram/files/3344494/gulpfile.js.zip)
I made a few changes to gulpfile.js. It works for me. Also, I modified some code as it was running build twice. Use any file differ to see the changes.

**Comment by renhaoweixiao** [comment]
> [gulpfile.js.zip](https://github.com/zhukov/webogram/files/3344494/gulpfile.js.zip)
> 我对[gulpfile.js](https://github.com/zhukov/webogram/files/3344494/gulpfile.js.zip)做了一些更改。这个对我有用。此外，我修改了一些代码，因为它运行构建两次。使用任何不同的文件来查看更改。

good,build success

**Comment by renhaoweixiao** [comment]
> [gulpfile.js.zip](https://github.com/zhukov/webogram/files/3344494/gulpfile.js.zip)
> I made a few changes to gulpfile.js. It works for me. Also, I modified some code as it was running build twice. Use any file differ to see the changes.

build success, nice

**Comment by MatamVamshiKrishna** [comment]
> > [gulpfile.js.zip](https://github.com/zhukov/webogram/files/3344494/gulpfile.js.zip)
> > I made a few changes to gulpfile.js. It works for me. Also, I modified some code as it was running build twice. Use any file differ to see the changes.
> 
> build success, nice

Hi, this fix is incorrect. I am making another change. I will let you know once done.

**Comment by MatamVamshiKrishna** [comment]
The problem is with the older version of the gulp-manifest module, we replace this with the gulp-manifest3 module, which fixes this vinyl error. 
[webogram-fix.zip](https://github.com/zhukov/webogram/files/3346456/webogram-fix.zip)

**Comment by renhaoweixiao** [comment]
> The problem is with the older version of the gulp-manifest module, we replace this with the gulp-manifest3 module, which fixes this vinyl error.
> [webogram-fix.zip](https://github.com/zhukov/webogram/files/3346456/webogram-fix.zip)

nice, I am going to use websoket to develop a project, which will use some logic of webogram.

**Comment by tuan773388** [comment]
267
