### ISSUE TITLE
Error when searching in dialogs

### ISSUE THREAD

**Issue by IPRIT** [zhukov/webogram#700]
If you type "@" in the search, the server will return an error

```
Method: messages.search
Result: {"_":"rpc_error","error_code":400,"error_message":"SEARCH_QUERY_EMPTY"}
Stack: Error
at d (https://web.telegram.org/js/app.js:16:24163)
at https://web.telegram.org/js/app.js:16:25153
at c (https://web.telegram.org/js/app.js:8:6393)
at https://web.telegram.org/js/app.js:8:6565
at u.$eval (https://web.telegram.org/js/app.js:8:13762)
at u.$digest (https://web.telegram.org/js/app.js:8:12258)
at u.scopePrototype.$digest (chrome-extension://ighdmehidhipcmcojjgiloacoafjmpfk/dist/hint.js:1468:23)
at https://web.telegram.org/js/app.js:8:13847
at r (https://web.telegram.org/js/app.js:7:710)
at https://web.telegram.org/js/app.js:7:2708
```

**Comment by ArtemFitiskin** [comment]
Also %

**Comment by IPRIT** [comment]
All non-alphabetical characters.
