### ISSUE TITLE
Password protected accounts not supported

### ISSUE THREAD

**Issue by javierprovecho** [zhukov/webogram#777]
When trying to login into Chrome packaged webapp with a password protected account:

```
Method: auth.sendCode
Result: {"_":"rpc_error","error_code":400,"error_message":"PHONE_PASSWORD_PROTECTED"}
Stack: Error
    at d (chrome-extension://clhhggbfdinjmjhajaheehoeibfljjno/js/app.js:16:24325)
    at c (chrome-extension://clhhggbfdinjmjhajaheehoeibfljjno/js/app.js:8:6393)
    at chrome-extension://clhhggbfdinjmjhajaheehoeibfljjno/js/app.js:8:6565
    at u.$eval (chrome-extension://clhhggbfdinjmjhajaheehoeibfljjno/js/app.js:8:13762)
    at u.$digest (chrome-extension://clhhggbfdinjmjhajaheehoeibfljjno/js/app.js:8:12258)
    at chrome-extension://clhhggbfdinjmjhajaheehoeibfljjno/js/app.js:8:13847
    at r (chrome-extension://clhhggbfdinjmjhajaheehoeibfljjno/js/app.js:7:740)
    at chrome-extension://clhhggbfdinjmjhajaheehoeibfljjno/js/app.js:7:2738
    at n (chrome-extension://clhhggbfdinjmjhajaheehoeibfljjno/js/app.js:2:14860)
```

**Comment by zhukov** [comment]
Duplicate #766
