### ISSUE TITLE
Overwriting an already existing file

### ISSUE THREAD

**Issue by TimDaub** [zhukov/webogram#780]
Someone sends me a file and I already have it on my drive.
Now, I want to save that exact file at the exact same location: Essentially, I want to overwrite the old file with the new one.

Everytime I'm trying to do this, I get the following error:
"One of the params is missing or invalid"
```
Method: upload.getFile
Result: {"_":"rpc_error","error_code":400,"error_message":"OFFSET_INVALID"}
Stack: Error
    at h (chrome-extension://clhhggbfdinjmjhajaheehoeibfljjno/js/app.js:16:25254)
    at chrome-extension://clhhggbfdinjmjhajaheehoeibfljjno/js/app.js:16:26472
    at l (chrome-extension://clhhggbfdinjmjhajaheehoeibfljjno/js/app.js:8:6393)
    at chrome-extension://clhhggbfdinjmjhajaheehoeibfljjno/js/app.js:8:6565
    at u.$eval (chrome-extension://clhhggbfdinjmjhajaheehoeibfljjno/js/app.js:8:13762)
    at u.$digest (chrome-extension://clhhggbfdinjmjhajaheehoeibfljjno/js/app.js:8:12258)
    at chrome-extension://clhhggbfdinjmjhajaheehoeibfljjno/js/app.js:8:13847
    at r (chrome-extension://clhhggbfdinjmjhajaheehoeibfljjno/js/app.js:7:740)
    at chrome-extension://clhhggbfdinjmjhajaheehoeibfljjno/js/app.js:7:2738
    at n (chrome-extension://clhhggbfdinjmjhajaheehoeibfljjno/js/app.js:2:15181)
```

When I now rename the file to a unique name, I can easily download it without an error.

BTW: If you can point me to the exact location of the bug, I might fix it myself :)

**Comment by TimDaub** [comment]
Cool, thanks :) 

Btw: I love webogram!
