### ISSUE TITLE
Web Telegram is not working in Windows10 Edge

### ISSUE THREAD

**Issue by SenthilManickavel** [zhukov/webogram#902]
Web Telegram is not working in Windows10 Edge....

it gives error as check you internet connection (after entering mobile number)
 Error
Method: auth.sendCode
Result: {"data":null,"status":0,"config":{"method":"POST","transformRequest":null,"transformResponse":[null],"responseType":"arraybuffer","url":"https://venus.web.telegram.org/apiw1","data":{"0":0,"1":0,"2":1822556340,"3":1441910896,"4":20,"5":1615239032,"6":-74795706,"7":-1517973337,"8":13458256,"9":-2015458111},"headers":{}},"statusText":""}
Stack: Error
   at h (https://web.telegram.org/js/app.js:16:25962)
   at l (https://web.telegram.org/js/app.js:8:6383)
   at Anonymous function (https://web.telegram.org/js/app.js:8:6565)
   at u.prototype.$eval (https://web.telegram.org/js/app.js:8:13751)
   at u.prototype.$digest (https://web.telegram.org/js/app.js:8:12250)
   at u.prototype.$apply (https://web.telegram.org/js/app.js:8:14016)
   at l (https://web.telegram.org/js/app.js:7:22417)
   at f (https://web.telegram.org/js/app.js:7:24226)
   at w (https://web.telegram.org/js/app.js:7:24821)

**Comment by zhukov** [comment]
Can't reproduce this. Works fine for me.

**Comment by zhukov** [comment]
@SenthilManickavel ping
