### ISSUE TITLE
Adding bot to channels

### ISSUE THREAD

**Issue by Amir-Mousavi** [zhukov/webogram#948]
Hi, yesterday Telegram announced that our bot can become an administrator in our channel and post there.
https://core.telegram.org/bots/api#recent-changes

But when I tried to add my bot to my channel I got the below error:
**Error
One of the params is missing or invalid.
**
`Method: messages.addChatUser
Result: {"_":"rpc_error","error_code":400,"error_message":"CHAT_ID_INVALID"}
Stack: Error
    at h (https://web.telegram.org/js/app.js:30:3722)
    at https://web.telegram.org/js/app.js:30:4940
    at l (https://web.telegram.org/js/app.js:15:10195)
    at https://web.telegram.org/js/app.js:15:10367
    at m.$eval (https://web.telegram.org/js/app.js:15:17773)
    at m.$digest (https://web.telegram.org/js/app.js:15:16204)
    at https://web.telegram.org/js/app.js:15:17860
    at a (https://web.telegram.org/js/app.js:14:1293)
    at https://web.telegram.org/js/app.js:14:2747
    at n (https://web.telegram.org/js/app.js:3:17045)`

**Comment by zhukov** [comment]
The bots can be added just as administrators. We don't have administrators list for channels at the moment, so you can't add bots via Webogram for now.

**Comment by Amir-Mousavi** [comment]
Thank you :)
