### ISSUE TITLE
can't run in C9

### ISSUE THREAD

**Issue by Elvenisboy** [zhukov/webogram#949]
in C9 IDE ,i run 
```
npm install gulp -g
npm install
```

and run

```
gulp watch
```

it throw error, like this

```
 
/home/ubuntu/workspace/webogram/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/node_modules/globule/node_modules/lodash/dist/lodash.js:1051
  /**
  ^^^

SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:413:25)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/ubuntu/workspace/webogram/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/node_modules/globule/lib/globule.js:14:9)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
```

**Comment by zhukov** [comment]
Did you try to do the same without that IDE?

**Comment by Elvenisboy** [comment]
Yes,I try it in my computer

**Comment by zhukov** [comment]
And what was the result?
What is your OS / node.js version?

**Comment by Elvenisboy** [comment]
windows and linux
try 0.10.x,0.12.x,4.0 version

**Comment by zhukov** [comment]
I have gulp v3.9.0, nodejs v0.10.29, npm v1.4.14 and verything works fine. Try installing everything from scratch.

Btw, you forgot `sudo` for the first command in your first message.

```
sudo npm install -g gulp
npm install
```

If that doesn't help, I'm afraid there is something wrong with your configuration, but there is nothing to do with Webogram.

**Comment by Elvenisboy** [comment]
en, I really forgot ```sudo```
